name: CI-CD
on:
push:
branches: [ main ]
pull_request:
branches: [ main ]


env:
IMAGE_NAME: sample-microservice


jobs:
terraform-scan:
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v4
  - name: Setup Python (for checkov)
uses: actions/setup-python@v4
with:
python-version: '3.x'
  - name: Install Checkov
run: pip install checkov
  - name: Run Checkov
run: checkov -d terraform || true
  - name: Terrascan
uses: accurics/terrascan-action@master
with:
scan_type: 'iac'
severity: 'LOW'


build-and-deploy:
needs: terraform-scan
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v4
  - name: Setup Docker Buildx
uses: docker/setup-buildx-action@v2


  - name: Login to ACR
uses: azure/docker-login@v1
with:
login-server: ${{ secrets.ACR_LOGIN_SERVER }}
username: ${{ secrets.ACR_USERNAME }}
password: ${{ secrets.ACR_PASSWORD }}


  - name: Build and push image
run: |
  docker build -t ${{ env.IMAGE_NAME }}:latest ./app
  docker tag ${{ env.IMAGE_NAME }}:latest ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
  docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest


- name: Set up kubectl
uses: azure/setup-kubectl@v4
with:
version: 'latest'


  - name: Get AKS